### ISSUE TITLE
Our job names are too long

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/release#1091]
```
 {"component":"tide","level":"warning","msg":"Removing invalid label: key - prow.k8s.io/job, value - test_pull_request_openshift_ansible_extended_conformance_install, error: [must be no more than 63 characters]","time":"2018-07-24T22:11:36Z"}
```

/cc @smarterclayton

**Comment by smarterclayton** [comment]
Wow

On Jul 24, 2018, at 6:13 PM, Steve Kuznetsov <notifications@github.com>
wrote:

 {"component":"tide","level":"warning","msg":"Removing invalid label:
key - prow.k8s.io/job, value -
test_pull_request_openshift_ansible_extended_conformance_install,
error: [must be no more than 63
characters]","time":"2018-07-24T22:11:36Z"}

/cc @smarterclayton <https://github.com/smarterclayton>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/release/issues/1091>, or mute the thread
