### ISSUE TITLE
Use the Journal export format?

### ISSUE THREAD

**Issue by wking** [openshift/release#1217]
We're currently extracting journals directly from the node disks (e.g. [here][1]).  Journalctl's on-disk format is described [here][2].  However, for export to other hosts, the journalctl docs suggest using [the export format][3], which is likely more stable.  For example, it is more likely to be readable on hosts with other `journalctl` versions, while the non-export file format is not.  Should we adjust those `oc get --request-timeout=20s --raw /api/v1/nodes/$i/proxy/logs/journal/${j}system.journal` calls to use the host `journalctl -o export`?

CC @smarterclayton

[1]: https://github.com/openshift/release/blob/61fc33ad194d9793dd9e3345bef8596dbe1961d7/ci-operator/templates/cluster-launch-installer-e2e.yaml#L284-L286
[2]: https://www.freedesktop.org/wiki/Software/systemd/journal-files/
[3]: https://www.freedesktop.org/wiki/Software/systemd/export/

**Comment by smarterclayton** [comment]
There’s not way I know of to do that without SSH to the box which we are
trying to avoid (going forward we want to be able to do this without that
use case).

I wrote a simple go journal exporter that I can share for the near term.
Further out, we could have a new endpoint that lets us get that info
remotely.

The journal format is actually really stable, so I’m not as worried as I
would be normally.

On Aug 20, 2018, at 12:51 PM, W. Trevor King <notifications@github.com>
wrote:

We're currently extracting journals directly from the node disks (e.g. here
<https://github.com/openshift/release/blob/61fc33ad194d9793dd9e3345bef8596dbe1961d7/ci-operator/templates/cluster-launch-installer-e2e.yaml#L284-L286>).
Journalctl's on-disk format is described here
<https://www.freedesktop.org/wiki/Software/systemd/journal-files/>.
However, for export to other hosts, the journalctl docs suggest using the
export format <https://www.freedesktop.org/wiki/Software/systemd/export/>,
which is likely more stable. For example, it is more likely to be readable
on hosts with other journalctl versions, while the non-export file format
is not. Should we adjust those oc get --request-timeout=20s --raw
/api/v1/nodes/$i/proxy/logs/journal/${j}system.journal calls to use the
host journalctl --output=export?

CC @smarterclayton <https://github.com/smarterclayton>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/release/issues/1217>, or mute the thread

**Comment by wking** [comment]
> The journal format is actually really stable, so I’m not as worried as I would be normally. 

Am I just doing something wrong then?

```console
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/142/pull-ci-origin-installer-e2e-aws/536/artifacts/e2e-aws/nodes/ip-10-0-129-138.ec2.internal/journal.gz | zcat >journal
$ hexdump -C journal | head -n2
00000000  4c 50 4b 53 48 48 52 48  00 00 00 00 01 00 00 00  |LPKSHHRH........|
00000010  01 00 00 00 00 00 00 00  91 dc 3e 00 06 c7 41 5b  |..........>...A[|
$ journalctl --file journal 
Failed to open files: Invalid argument
$ journalctl --version
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN
$ head -n3 /etc/os-release 
NAME="Red Hat Enterprise Linux Workstation"
VERSION="7.5 (Maipo)"
ID="rhel"
```

**Comment by smarterclayton** [comment]
Wierd, I thought it was --path.

https://github.com/smarterclayton/journalread is the read library I
created, the cmd takes a file as argument and then spits out timestamp and
then MESSAGE=.  There's still some weirdness with the compression format I
couldn't fix (I needed something that worked on Mac)

**Comment by stevekuznetsov** [comment]
This cannot be fixed in our CI, and issues should be raised in `smarterclayton/journalread`
/close
