### ISSUE TITLE
Cluster Operator PR checks are failing with ci-operator errors

### ISSUE THREAD

**Issue by twiest** [openshift/release#1338]
/kind bug

/area test-results

## What did you expect to happen?

The PR Checks to execute and give output relevant to that check.

## What happened?

Here's an example our the cluster operator verify check output:

```
2018/08/31 19:12:14 Resolved source https://github.com/openshift/cluster-operator to master@02e99800, merging: #334 48897ad8 @twiest
2018/08/31 19:12:15 Resolving inputs for the test
2018/08/31 19:12:15 Ran for 0s
error: could not resolve inputs: could not determine inputs for step [input:root]: could not resolve base image: imagestreamtags.image.openshift.io "cluster-operator-test-base:" is forbidden: User "system:serviceaccount:ci:ci-operator" cannot get imagestreamtags.image.openshift.io in the namespace "stable": no RBAC policy matched
```

## How can the error be reproduced?

Yes. Running "/test verify" caused the same test to fail a 2nd time.

## Is there anything else we need to know?

I don't believe this is my PR that's failing the checks as the same checks run successfully on my local machine.

**Comment by stevekuznetsov** [comment]
@twiest thanks for the issue report. It looks like you have provided the `test_base_image` as part of your `base_images` list, whereas we require it as a top-level key in your CI Operator configuration. So, instead of:

```json
{
  "base_images": {
    "test_base_image": {
      "cluster": "https://api.ci.openshift.org",
      "namespace": "openshift",
      "name": "release",
      "tag": "golang-1.10"
    }
  },
}
```

Please re-work your `ci-operator` configuration to look like:
```json
{
  "test_base_image": {
    "cluster": "https://api.ci.openshift.org",
    "namespace": "openshift",
    "name": "release",
    "tag": "golang-1.10"
  }
}
```

I've created a JIRA ticket to track work on better validation for CI Operator configuration so we can catch this issue programatically. https://jira.coreos.com/browse/DPTP-150

**Comment by twiest** [comment]
@stevekuznetsov  I haven't.

I believe @csrwng made the changes, though.

@csrwng is that correct?     Can this issue be closed?

**Comment by csrwng** [comment]
Yes I made the change, this issue can be closed.
