### ISSUE TITLE
tools/populate-owners should allow for updates to OWNERS from one repo

### ISSUE THREAD

**Issue by tnozicka** [openshift/release#1601]
I am running `go run tools/populate-owners/main.go` and it takes longer and longer every day as more repos go in. Even just cloning origin isn't fun. The issue is that you clone the whole repo to get about 2 files `/OWNERS` and `/OWNER_ALIASES`, right? Why not get those specific files from GitHub url? The whole script would be reduced from tens of minutes to few seconds.

/kind question
/cc @wking @stevekuznetsov

**Comment by wking** [comment]
> I am running go run tools/populate-owners/main.go and it takes longer and longer every day as more repos go in.

We can probably do parallel retrieval without too much trouble on our end, but that might hit a GitHub quota limit or some such (or maybe not, I dunno).  The old script [used to be parallel][1], and it worked fine.

> The issue is that you clone the whole repo to get about 2 files /OWNERS and /OWNER_ALIASES, right? Why not get those specific files from GitHub url?

Because then you'd have to give the script an API token for the private repos.  Some discussion of this and alternatives in the e1f993fb1debc commit message.  My favorite fix would be for GitHub to enable the `git-upload-archive` command, but I guess they have denial-of-service concerns.

[1]: https://github.com/openshift/release/pull/1285/commits/e1f993fb1debc43d81f7c413cd4fea39077d48b4#diff-6d291a5a9e109cf49cdbee42e7836f00L36

**Comment by stevekuznetsov** [comment]
We can:
 - do a depth=1 clone (don't we already? I am not sure you're right that we clone the entire repo)
 - parallelize the clones (but do it so you don't DOS the host)
 - expose a org/repo arg to just update one OWNERS set

Last option probably easiest?

**Comment by stevekuznetsov** [comment]
I think that archive is not possible with GitHub hosts -- that's what @wking was looking into. Let's just expose the specific org/repo and run only that

**Comment by wking** [comment]
> do a depth=1 clone (don't we already? I am not sure you're right that we clone the entire repo)

Yeah, we [do this already][1].  And I expect @tnozicka's meant "whole HEAD tree" ;).

[1]: https://github.com/openshift/release/blob/ad28e5cd850d3c8ae57894833c1107b987f97629/tools/populate-owners/main.go#L118

**Comment by tnozicka** [comment]
oh, github...
I agree that having a flag to chose the specific repo is going to be simplest and actually helps me avoid filtering out all the other files at git level ;)
