### ISSUE TITLE
missing image failures in AWS based origin test jobs

### ISSUE THREAD

**Issue by bparees** [openshift/release#2026]
```
1. Hosts:    localhost
     Play:     Create OpenShift certificates for master hosts
     Task:     Pull CLI Image
     Message:  Error pulling docker.io/openshift/origin-node - code: None message: manifest for docker.io/openshift/origin-node:14c1ee7 not found
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install/16468/consoleFull#58123552758b6e51eb7608a5981914356

Looks like all the jobs that extend from `origin_built_installed_release.yml` are being impacted.

**Comment by smarterclayton** [comment]
Yes, it started failing about the time 
https://github.com/openshift/openshift-ansible/pull/10277 was merged.  I disabled the job, since it was only accidentally being included and we're about to nuke that.

However, for some reason skip and refresh are not taking effect.

**Comment by bparees** [comment]
> I disabled the job, since it was only accidentally being included and we're about to nuke that.

@smarterclayton disabled what job?

This also affects extended_builds, extended_image_ecosystem, and extended_image_registry, so until those are replaced we need that coverage

**Comment by smarterclayton** [comment]
Let’s get those switched.

Note that I fixed the core job, but I also disabled
extended_conformance_installz

On Oct 26, 2018, at 9:32 AM, Ben Parees <notifications@github.com> wrote:

I disabled the job, since it was only accidentally being included and we're
about to nuke that.

@smarterclayton <https://github.com/smarterclayton> disabled what job?

This also affects extended_builds, extended_image_ecosystem, and
extended_image_registry, so until those are replaced we need that coverage

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/release/issues/2026#issuecomment-433408552>,
or mute the thread

**Comment by bparees** [comment]
Switched to what?  They can't run on top of e2e-aws yet since the registry doesn't come up without help.

I already have a version of extended_builds that runs against GCP, that we run in the openshift/builder repo.

**Comment by richm** [comment]
Do we just need to add this definition when we deploy the cluster?
```
-e openshift_cli_image="openshift/origin-node{OPENSHIFT_IMAGE_TAG$( cat ./ORIGIN_IMAGE_TAG )}"
```
?

**Comment by richm** [comment]
something like this?  https://github.com/openshift/aos-cd-jobs/pull/1630
