### ISSUE TITLE
Things with image change triggers can use the config updater in 3.10

### ISSUE THREAD

**Issue by kargakis** [openshift/release#705]
We don't use the [config-updater plugin](https://github.com/openshift/release/tree/master/cluster/ci/config/prow/openshift/config-updater) today to update things like DeploymentConfigs with ICTs since the image field is getting dropped during the update. This seems to be fixed in 3.10, so we should re-evaluate using the config updater.

@bbguimaraes @stevekuznetsov

**Comment by kargakis** [comment]
@tnozicka @mfojtik there is still service disruption involved here and it kind of sucks. This is actually super racy because I may or may not get redeployed.

**Comment by tnozicka** [comment]
> @tnozicka @mfojtik there is still service disruption involved here and it kind of sucks. This is actually super racy because I may or may not get redeployed.

Could you elaborate on this?

**Comment by kargakis** [comment]
> @kargakis Could you elaborate on this? What, and how does it happen?

When I `oc apply` my changes, the image field is dropped, a rollout starts, then your fix comes into play and updates the image back, then another rollout starts.

**Comment by tnozicka** [comment]
@kargakis you are not allowed to specify an image when using image trigger - put an `" "` and it should work fine.

**Comment by kargakis** [comment]
ugh, is this documented anywhere?

**Comment by tnozicka** [comment]
`s/you are not allowed/you shouldn't`

> ugh, is this documented anywhere?

GH issues an BZ only likely - but it is a logical (although not obvious) consequence of meaning of those fields. If you specify an IS trigger you want image from there so there is no need to specify image, nor you have the knowledge to specify it correctly. If you set both image and IS trigger that's basically undefined behaviour - we explicitly prevent it for the first deployment but when you do `oc apply` with an image specified you are telling it to replace the image no matter what but because you have IS trigger that will reconcile it eventually to the desired state.

**Comment by kargakis** [comment]
I think it's worth documenting somewhere. Far from obvious even for me.
