### ISSUE TITLE
Prometheus warning in api.ci

### ISSUE THREAD

**Issue by kargakis** [openshift/release#757]
```
level=warn ts=2018-04-06T09:58:07.184988376Z caller=manager.go:339 component="rule manager" group=aggregate_container_resources msg="Evaluating rule failed" rule="record: container_cpu_usage_percent_by_host\nexpr: sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[5m])) BY (hostname, type)\n  / ON(hostname, type) machine_cpu_cores\n" err="many-to-many matching not allowed: matching labels must be unique on one side"
```
@smarterclayton

**Comment by smarterclayton** [comment]
Was fixed upstream, I haven’t patched yet

On Apr 6, 2018, at 8:18 AM, Michalis Kargakis <notifications@github.com>
wrote:

level=warn ts=2018-04-06T09:58:07.184988376Z caller=manager.go:339
component="rule manager" group=aggregate_container_resources
msg="Evaluating rule failed" rule="record:
container_cpu_usage_percent_by_host\nexpr:
sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[5m])) BY
(hostname, type)\n  / ON(hostname, type) machine_cpu_cores\n"
err="many-to-many matching not allowed: matching labels must be unique
on one side"

@smarterclayton <https://github.com/smarterclayton>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/release/issues/757>, or mute the thread
