### ISSUE TITLE
Image pruning failure

### ISSUE THREAD

**Issue by kargakis** [openshift/release#885]
```
Failed to build graph!

The following objects have invalid references:

  ReplicaSet[ci/rpm-mirror-678f6dcf6]: invalid docker image reference " ": invalid reference format
  ReplicaSet[ci/rpm-mirror-6b94f7f8cc]: invalid docker image reference " ": invalid reference format
  ReplicaSet[ci/rpm-mirror-75984654b5]: invalid docker image reference " ": invalid reference format
  ReplicaSet[ci/rpm-mirror-88dd7bbc7]: invalid docker image reference " ": invalid reference format

Either fix the references or delete the objects to make the pruner proceed.
Client version (v3.9.0-alpha.3+78ddc10) doesn't match master (v3.10.0-alpha.0+865022c-1018), which may allow for different image references. Try to re-run this binary with the same version.
error: failed to build graph - no changes made
```
@smarterclayton

**Comment by kargakis** [comment]
Hrm, should be fixed by https://github.com/openshift/release/commit/7e77cfa15c0a753d3c83c93b3db27cd5921d3e79 but we never propagated that change in the cluster.

**Comment by smarterclayton** [comment]
Yikes - we need to get a fix in to origin fast and bump api ci

On May 23, 2018, at 5:17 AM, Michalis Kargakis <notifications@github.com>
wrote:

Failed to build graph!

The following objects have invalid references:

  ReplicaSet[ci/rpm-mirror-678f6dcf6]: invalid docker image reference
" ": invalid reference format
  ReplicaSet[ci/rpm-mirror-6b94f7f8cc]: invalid docker image reference
" ": invalid reference format
  ReplicaSet[ci/rpm-mirror-75984654b5]: invalid docker image reference
" ": invalid reference format
  ReplicaSet[ci/rpm-mirror-88dd7bbc7]: invalid docker image reference
" ": invalid reference format

Either fix the references or delete the objects to make the pruner proceed.
Client version (v3.9.0-alpha.3+78ddc10) doesn't match master
(v3.10.0-alpha.0+865022c-1018), which may allow for different image
references. Try to re-run this binary with the same version.
error: failed to build graph - no changes made

@smarterclayton <https://github.com/smarterclayton>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/release/issues/885>, or mute the thread
